project05/config/routes.rb
Articles::Application.routes.draw do
  resources :authors

  resources :articles

  root :to => 'articles#index'

end

project05/app/models/article.rb
class Article < ActiveRecord::Base
	validates :title, :body, presence: true

	belongs_to :author

	before_save :increment_times_edited

	private
	def increment_times_edited
		self.times_edited += 1 unless self.new_record?
	end

	
	

end

project05/app/models/author.rb
class Author < ActiveRecord::Base
	validates_presence_of :name
	has_attached_file :image
	has_many :articles

	validate :no_author_named_pat

	private
	def no_author_named_pat
		errors[:base] << ("Author name may not be 'Pat'") if name.downcase.include? "pat"
	end
end

project05/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :set_edit_return_url, :only => [:edit]
  before_filter :load_authors, :only => [:new, :edit, :update, :create]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.paginate page: params[:page], per_page: 10
    @total_articles = Article.select(:all)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @article = Article.new
    

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render action: "new" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        #format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.html { redirect_to session[:edit_redirect], notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end

  private
    def set_edit_return_url
      session[:edit_redirect] = request.referer
    end

    def load_authors
      @authors = Author.all
    end
end

project05/app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.paginate page: params[:page], per_page: 10

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @authors }
    end
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
    @author = Author.find(params[:id])
    @articles_for_author = Article.find_all_by_author_id(@author.id)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @author }
    end
  end

  # GET /authors/new
  # GET /authors/new.json
  def new
    @author = Author.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @author }
    end
  end

  # GET /authors/1/edit
  def edit
    @author = Author.find(params[:id])
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(params[:author])

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render json: @author, status: :created, location: @author }
      else
        format.html { render action: "new" }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /authors/1
  # PUT /authors/1.json
  def update
    @author = Author.find(params[:id])

    respond_to do |format|
      if @author.update_attributes(params[:author])
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author = Author.find(params[:id])
    @author.destroy

    respond_to do |format|
      format.html { redirect_to authors_url }
      format.json { head :no_content }
    end
  end
end

project05/app/helpers/articles_helper.rb
module ArticlesHelper
end

project05/app/helpers/authors_helper.rb
module AuthorsHelper
end

project05/app/views/authors/_form.html.haml
= form_for(@author, :html => { :multipart => true }) do |f|
  - if @author.errors.any?
    #error_explanation
      %h2
        = pluralize(@author.errors.count, "error")
        prohibited this author from being saved:
      %ul
        - @author.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field_label
    = f.label :image
  .field
    = f.file_field :image
  .actions
    = f.submit

project05/app/views/authors/edit.html.haml
%h2.subtitle ...my sister said enjoy the articles. You'd better. She's good with a bow and arrow...
%ul.menubar
  %li= link_to "articles", articles_path
  %li= link_to "authors", authors_path
= render 'form'
= link_to 'Show', @author
|
\#{link_to 'Back', authors_path}

project05/app/views/authors/index.html.haml
%h2.subtitle ...Pat, you betrayed me! I wanted to play with the blocks first!
%ul.menubar
  %li= link_to "articles", articles_path
  %li= link_to "authors", authors_path
#new_author
  \#{link_to image_tag('add.png'), new_author_path, :title => "create new author"}
  \#{link_to 'New Author', new_author_path, :title => "create new author"}
%p.pagination_bar= will_paginate @authors
%table#author_list
  %thead
    %tr
      %th Name
      %th 
      %th 
      %th 
  %tbody
    - @authors.each do |author|
      %tr
        %td= author.name
        %td= link_to image_tag('zoom.png'), author, :title => "view author"
        %td= link_to image_tag('application_form_edit.png'), edit_author_path(author), :title => "edit author"
        %td= link_to image_tag('delete.png'), author, confirm: 'Are you sure?', method: :delete, :title => "delete author"
%br/
%p.pagination_bar= will_paginate @authors

project05/app/views/authors/new.html.haml
%h2.subtitle ...I can count in Spanish: uno - wait, I can't find the squiggly thing that goes over the 'n'!
%ul.menubar
  %li= link_to "articles", articles_path
  %li= link_to "authors", authors_path
= render 'form'
= link_to 'Back', authors_path

project05/app/views/authors/show.html.haml
%h2.subtitle ...world domination! Oh, um... No, not really.

%p#notice= notice
%ul.menubar
  %li= link_to "articles", articles_path
  %li= link_to "authors", authors_path
%ul.menu
  %li
    = link_to image_tag('arrow_left.png'), articles_path, :title => 'back to list'
    = link_to 'list all authors', authors_path, :title => 'back to list'
  %li
    = link_to image_tag('application_form_edit.png'), edit_author_path(@author), :title => 'edit author'
    = link_to 'edit', edit_author_path(@author), :title => 'edit author'
  %li
    = link_to image_tag('delete.png'), @author, :confirm => "Are you sure?", :method => :delete, :title => 'delete author'
    = link_to 'delete author', @author, :confirm => "Are you sure?", :method => :delete, :title => 'delete author'
%br/

%h2
  %b Name:
  = @author.name

= image_tag @author.image.url

%table#article_list_for_author
  %thead
    %tr
      %th Title
      %th Body
      %th Created at
      %th
  %tfoot
    %td{:colspan => "5"}
      %p
        = pluralize(@articles_for_author.size, 'article')
        \.
  %tbody
    - @articles_for_author.each do |article|
      %tr
        %td= h article.title
        %td= truncate(strip_tags(article.body), length: 20)
        %td= article.created_at.to_s(:datetime)
        %td= link_to image_tag('zoom.png'), article, :title => "view article"
        %td= link_to image_tag('application_form_edit.png'), edit_article_path(article), :title => "edit article"
        %td= link_to image_tag('delete.png'), article, confirm: 'Are you sure?', method: :delete, :title => "delete article"
%br/

= link_to 'Edit', edit_author_path(@author)
|
\#{link_to 'Back', authors_path}

project05/app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Articl.es - All the World's Articles (with a name .com hipsters love)
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body{:class => controller.controller_name}
    %h1 Articl.es
    = yield