project06/config/routes.rb
Gamez::Application.routes.draw do
  root :to => "games#index"

  resources :games

  devise_for :users,  :controllers => { :registrations => "users/registrations" }

end

project06/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities

    user ||= User.new
    #user.role = "guest"
    if user.role.eql?( "admin" )
        can :manage, :all
    end
    #if user.role.nil?
    #    can :read, Game
    #    can :create, User
    #else
#
 #       if user.role.eql?( "admin" )
  #          can :manage, :all
   #     elsif user.role.eql( "member" )
    #        can :read, Game
     #       can [:update, :delete], Game, :user_id => user.id
      #      can :update, User, :user_id => user.id
       # else
        #    can :read, Game
         #   can :manage, User
       # end
   # end
end
end

project06/app/models/game.rb
class Game < ActiveRecord::Base
  attr_accessible :title, :rating
end

project06/app/models/user.rb
class User < ActiveRecord::Base

  ROLES = %w[admin member guest]
  # Include default devise modules. Others available are:
  # :token_authenticatable, :lockable, :timeoutable, :confirmable, :activatable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :role
end

project06/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
  	flash[:error] = exception.message
  	redirect_to root_url
  end
end

project06/app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.all
  end

  def show
    @game = Game.find(params[:id])
  end

  def new
    @game = Game.new
  end

  def create
    @game = Game.new(params[:game])
    if @game.save
      redirect_to @game, :notice => "Successfully created game."
    else
      render :action => 'new'
    end
  end

  def edit
    @game = Game.find(params[:id])
  end

  def update
    @game = Game.find(params[:id])
    if @game.update_attributes(params[:game])
      redirect_to @game, :notice  => "Successfully updated game."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @game = Game.find(params[:id])
    @game.destroy
    redirect_to games_url, :notice => "Successfully destroyed game."
  end
end

project06/app/controllers/user_controller.rb
class UserController < ApplicationController
	load_and_authorize_resource
end

project06/app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_filter :check_permissions
  skip_before_filter :require_no_authentication
 
  def check_permissions
    authorize! :create, resource
  end

  def create
  	if verify_recaptcha
  		super
  	else
  		build_resource
  		clean_up_passwords(resource)
  		flash.now[:alert] = "There was an error with the recaptcha code below. Please re-enter."
  		render_with_scope :new
  	end
  end
end

project06/app/helpers/application_helper.rb
module ApplicationHelper
end

project06/app/helpers/games_helper.rb
module GamesHelper
end

project06/app/helpers/user_helper.rb
module UserHelper
end

project06/app/views/games/_form.html.haml
= form_for @game do |f|
  = f.error_messages
  %p
    = f.label :title
    %br
    = f.text_field :title
  %p
    = f.label :rating
    %br
    = f.number_field :rating
  %p
    = f.submit

project06/app/views/games/edit.html.haml
= render 'form'

%p
  = link_to "Show", @game
  |
  = link_to "View All", games_path

project06/app/views/games/index.html.haml
%table
  %tr
    %th Title
    %th Rating
  - for game in @games
    %tr
      %td= game.title
      %td= game.rating
      %td= link_to 'Show', game
      %td= link_to 'Edit', edit_game_path(game)
      %td= link_to 'Destroy', game, :confirm => 'Are you sure?', :method => :delete

%p= link_to "New Game", new_game_path

project06/app/views/games/new.html.haml
= render 'form'

%p= link_to "Back to List", games_path

project06/app/views/games/show.html.haml
%p
  %strong Title:
  = @game.title
%p
  %strong Rating:
  = @game.rating

%p
  = link_to "Edit", edit_game_path(@game)
  |
  = link_to "Destroy", @game, :confirm => 'Are you sure?', :method => :delete
  |
  = link_to "View All", games_path

project06/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gamez</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<h1> <%= link_to 'Gamez', root_path %> </h1>
<div id="user_nav">
	<% if user_signed_in? %>
		Signed in as <%= current_user.email %> Not you? <%= link_to "log out", destroy_user_session_path %>
	<% else %>
		<%= link_to "log in", new_user_session_path %> or <%= link_to "register", new_user_registration_path %>
	<% end %>
</div>
<%= yield %>

</body>
</html>